# Generated by Django 2.0.1 on 2018-03-19 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sale_type', models.CharField(choices=[('retail', 'retail'), ('cash account', 'cash account'), ('credit account', 'credit account')], default='retail', max_length=50)),
                ('store_code', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('basket', 'basket'), ('complete', 'complete')], default='complete', max_length=50)),
                ('docket_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_excl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('identification_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pos_id', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_offering_id', models.CharField(max_length=50)),
                ('supplier_product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=150, null=True)),
                ('promotion_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price_channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price_calculation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_offering_price_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('sold', 'sold'), ('returned', 'returned')], default='sold', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_of_measure', models.CharField(choices=[('each', 'each'), ('kg', 'kg'), ('square metre', 'square metre'), ('lineal metre', 'metre')], default='each', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_excl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='app.Sale')),
                ('status_related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sale_items', to='app.Sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='app.Sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TenderType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TenderType'),
        ),
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalesChannel'),
        ),
    ]
